### ISSUE TITLE
Invalid MaxStartups value in sshd_config

### ISSUE THREAD

**Issue by loryeam** [Zanthed/infrastructure#1]
The `MaxStartups` value is invalid(?) and causes sshd to hang. It should be of the format start:rate:full according to the [documentation](https://man.archlinux.org/man/sshd_config.5#MaxStartups).

**Comment by Zanthed** [comment]
It's not invalid. It's just due to a new change in a recent OpenSSH update there are not enough file descriptors in the default OpenSSH service unit file.

Solution is https://github.com/GrapheneOS/infrastructure/commit/72937c922f49e4e98115b8e99de117cc0559a279

**Comment by Zanthed** [comment]
https://www.openssh.com/txt/release-8.9

 * All: convert all uses of select(2)/pselect(2) to poll(2)/ppoll(2).
   This includes the mainloops in ssh(1), ssh-agent(1), ssh-agent(1)
   and sftp-server(8), as well as the sshd(8) listen loop and all
   other FD read/writability checks. On platforms with missing or
   broken poll(2)/ppoll(2) syscalls a select(2)-based compat shim is
   available.

**Comment by Zanthed** [comment]
This change affects MaxStartups.
